# Site settings
title: Elliot Smith
email: elliot@smitec.io
description: > # this means to ignore newlines until "baseurl:"
    Elliot Smith - programming, startups and research
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://smitec.io" # the base hostname & protocol for your site
twitter_username: smitec
github_username:  smitec

# Build settings
markdown: kramdown

google_analytics: UA-72801463-1
